// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydduebczkzwgtdyyesuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZHVlYmN6a3p3Z3RkeXllc3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDA1NjAsImV4cCI6MjA2NDY3NjU2MH0.SggdcvP6sXM8lwaPpKAkdPOxSomfuc__Dai4vuE7Zkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);